# Generated by Django 2.2.6 on 2019-11-12 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asignaturaProf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('docente', models.CharField(default='', max_length=255)),
                ('periodo', models.CharField(default='', max_length=255)),
                ('nombre', models.CharField(default='', max_length=255)),
                ('grupo', models.IntegerField(default=0)),
                ('matriculados', models.IntegerField(default=0)),
                ('evaluaron', models.IntegerField(default=0)),
                ('p9', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('p10', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('p11', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('p12', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('p13', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('p14', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('p15', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('p16', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('p17', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('p18', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('p19', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('p20', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
            options={
                'db_table': 'asignatura_asignaturaprof',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(default='', max_length=1000)),
                ('polaridad', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('asignatura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignatura.asignaturaProf')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
