# Generated by Django 2.2.6 on 2020-01-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0002_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asignatura', models.CharField(default='', max_length=255)),
                ('profesor', models.CharField(default='', max_length=255)),
                ('top', models.IntegerField()),
            ],
        ),
    ]
