# Generated by Django 2.2.6 on 2019-12-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('pregunta', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('carrera', models.CharField(max_length=500)),
                ('asignatura', models.CharField(max_length=500)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
