# Generated by Django 2.2.6 on 2019-12-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField(default='', max_length=500)),
                ('descripcion', models.TextField(default='', max_length=1000)),
                ('carrera', models.CharField(default='', max_length=500)),
                ('asignatura', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
